/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'jess' at '4/27/15 3:42 PM' with Gradle 2.3
 *
 * @author jess, @date 4/27/15 3:42 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
